### ISSUE TITLE
qgis 2.6 & spatialite

### ISSUE THREAD

**Issue by andrei4002** [Oslandia/qgis-versioning#6] opened 2015-02-06 14:34 UTC
I'm trying to do a checkout operation in a sqlite store, but it gives me some weird error "insert on views_geometry_columns violates constraint: f_geometry_column value must be lower case" 

is it a spatialite issue? any ideas on this?

**Comment by vmora** [comment] 2015-02-06 14:53
On checkout, the conversion from the postgres DB to spatialite is done with ogr2ogr, could you uncomment the prints at line 222 and 243 in versionning_base.py

You can also set the verbose on the Db instance to view the SQL statements before they are executed.

**Comment by andrei4002** [comment] 2015-02-06 15:45
there seem to be some constraints (not sure if they are new or something) in spatialite that require the geometry column names in the views_geometry_columns and geometry_columns to be lowercase (in versioning_base.py, i see a lot of calls using GEOMETRY as a column name inserted.

There are also some other issues where a column named 'type' is called on views_geometry_columns, but the correct column name to be called is 'geometry_type'
There is a 'read_only(int)' column required to be inserted in the views_geometry_columns 

After these changes, the checkout and commit process seems to complete successfully (not really sure if I changed everything correctly in all the places, I haven't done thorough testing, just checkout, small change and commit)

I'll do a fork and commit to it, maybe you can check it out and see if I missed something or if my approach is wrong

**Comment by vmora** [comment] 2015-02-06 15:51
I thanks for that. There are a bunch of test scripts in the test directory. PR are welcome.

I'd like to know the version of your spatialite.

**Comment by andrei4002** [comment] 2015-02-06 15:52
any idea how to check the version? I'm just running osgeo4w with the latest qgis (2.6.1)

**Comment by vmora** [comment] 2015-02-06 16:02
in osgeo4w, in adavanced mode (for adding components) you have the versions.

**Comment by andrei4002** [comment] 2015-02-06 16:42
not sure which is which so here's a screenshot

![screen shot 2015-02-06 at 18 41 07](https://cloud.githubusercontent.com/assets/475334/6083232/c2b98ef4-ae2f-11e4-921f-69b40e0a1eee.png)

**Comment by vmora** [comment] 2015-02-06 16:47
4.4.1 thanks!

**Comment by andrei4002** [comment] 2015-02-24 09:49
any updates on this?

if it's not going to be fixed soon, can you recommend the latest version of qgis/spatialite that would work in the current form of the plugin?

**Comment by vmora** [comment] 2015-02-24 10:29
Unfortunately I won't have time to fix that soon.

I guess that a find/replace of "GEOMETRY" by "geometry" would fix the problem. Could you try this simple fix ?

**Comment by gignacnic** [comment] 2015-07-24 23:55
@andrei4002 & @vmora :
I have made a formal branch with fixes proposed in this ticket and @andrei4002 suggestions (see this url for my branch including two commits: https://github.com/GISeHealth/qgis-versioning/tree/fix_spatialite_4.x).  Using .../test/versioning_base_test.py, I have verified checkout & modification, it works fine now (QGIS 2.8.2 Linux Mint 17, PostgreSQL 9.4 and PostGIS 2.1.8), but committing the modified junction object in the test script results in a srid=0 in PG, this is the last problem before we could fix this issue in order that this plugin works for QGIS 2.8.x, see details here:

SELECT junctions_diff.geom, ST_AsText(junctions_diff.geom), ST_SRID(junctions_diff.geom), junctions_diff.elevation
FROM epanet_trunk_1_to_2_diff.junctions_diff; =>

geom (geometry);                            st_astext;      st_srid;    elevation
"01010000000000000000000000000000000000F03F";"POINT(0 1)";  0;          1
"01010000000000000000000000000000000000F03F";"POINT(0 1)";  0;          8

This table is the diff table, containing both the old and modified feature (elevation value is modified in the test script).

If we run the ogr2ogr command directly :

ogr2ogr -preserve_fid -f PostgreSQL PG:"dbname=epanet_test_db active_schema=epanet_trunk_1_to_2_diff" -lco GEOMETRY_NAME=geom -lco FID=jid /tmp/versioning_base_test1.sqlite junctions

We get a new "junctions" table in the "epanet_trunk_1_to_2_diff schema" and we can see the srid information contained in the spatialite test file is conveyed in PG :

SELECT junctions.geom, ST_AsText(junctions.geom), ST_SRID(junctions.geom), junctions.elevation
FROM epanet_trunk_1_to_2_diff.junctions; =>

geom (geometry(Point,2154));                         st_astext;         st_srid;    elevation
"01010000206A080000000000000000F03F0000000000000000";"POINT(1 0)";      2154;       0
"01010000206A0800000000000000000000000000000000F03F";"POINT(0 1)";      2154;       1
"01010000206A0800000000000000000000000000000000F03F";"POINT(0 1)";      2154;       8

Where the last two records are the old and modified POINT(0 1) feature.  

@andrei4002  : can you validate that checkout works fine now for you?  Any idea why we'd get the default srid=0 value upon commit instead of the good one (EPSG:2154)?

**Comment by vmora** [comment] 2015-07-26 17:51
@gignacnic did you try to print the ogr2ogr command issued by the versionning module to check that it matches the one that you use ? Normally it's a system call, so if it works on command line and it doesn't work as a python system call, then the problem is either a slightly diffirent command or a difference in environment variables (the later seems less likely to me).

**Comment by ymoisan** [comment] 2015-07-30 21:20
Here are my test results : 

I get the versioning_base_test.py to succeed when I explicitly add 

'-a_srs EPSG:2154'

in the ogr2ogr command in the python file : 

ipdb> cmd.insert(5, '-a_srs EPSG:2154')
ipdb> p cmd
['ogr2ogr', '-preserve_fid', '-f', 'PostgreSQL', u'PG:"dbname=epanet_test_db active_schema=epanet_trunk_1_to_2_diff"', '-a_srs EPSG:2154', '-lco', 'GEOMETRY_NAME=geom', '-lco', 'FID=jid', '/tmp/versioning_base_test1.sqlite', u'junctions_diff']

The diff table in PG now has the right SRID and thus it is merged correctly in the epanet schema.

SELECT *, ST_AsText(geom), ST_SRID(geom)
FROM epanet.junctions;

1;"0";0;;"";"01010000206A080000000000000000F03F0000000000000000";1;;;;"POINT(1 0)";2154
3;"1";8;;"";"01010000206A0800000000000000000000000000000000F03F";2;;2;;"POINT(0 1)";2154
2;"1";1;;"";"01010000206A0800000000000000000000000000000000F03F";1;1;;3;"POINT(0 1)";2154

Would there be a need to add the a_srs argument  e.g. : 

if pgeom:
            cmd.insert(5, '-lco')
            cmd.insert(6, 'GEOMETRY_NAME='+pgeom)
            cmd.insert(7,'-a_srs $some_way_to_find_srs')

Testing from the commandline, I get those intriguing results :  

mypromt  /tmp $ ogr2ogr -preserve_fid -f PostgreSQL PG:"dbname=epanet_test_db active_schema=epanet_trunk_1_to_2_diff" -lco GEOMETRY_NAME=geom -lco FID=jid /tmp/versioning_base_test1.sqlite junctions_diff

Srid=0, so consistent with the os.system call in the python test file.

mypromt /tmp $ ogr2ogr -preserve_fid -f PostgreSQL PG:"dbname=epanet_test_db active_schema=epanet_trunk_1_to_2_diff" -lco GEOMETRY_NAME=geom -lco FID=jid /tmp/versioning_base_test1.sqlite junctions_yves
FAILURE: Couldn't fetch requested layer 'junctions_yves'!

Sure enough, there is no such layer : 

mypromt /tmp $ ogrinfo versioning_base_test1.sqlite 

INFO: Open of `versioning_base_test1.sqlite'
      using driver `SQLite' successful.
1: junctions (Point)
2: pipes (Line String)

mypromt /tmp $ ogr2ogr -preserve_fid -f PostgreSQL PG:"dbname=epanet_test_db active_schema=epanet_trunk_1_to_2_diff" -lco GEOMETRY_NAME=geom -lco FID=jid /tmp/versioning_base_test1.sqlite junctions

Srid=2154.  OK now.

Question : why does "junctions_diff" work and not "junctions_*" ?  I'm on the command line here so there is no "_diff" string manipulation as far as I can see.

If noone has an idea, I'll try and work directly from the plugin in QGIS and see if it works there.

Cheers,

**Comment by gignacnic** [comment] 2015-08-02 00:48
@vmora : we found the problem it was not ogr2ogr problem, but a change I made at line 711:  geom = sql.find('geometry') != -1 that was not appropriate, which did not create the INSERT in the metadata geometry_columns in spatialite as suppose, just before the ogr2ogr command to PG. A PR has been to include fix for spatiality 4.x version include in the latest QGIS 2.8 version: https://github.com/Oslandia/qgis-versioning/pull/10

**Comment by gignacnic** [comment] 2015-08-11 12:05
We can close this issue, since it is resolved by this merge: https://github.com/Oslandia/qgis-versioning/pull/10

**Comment by vmora** [comment] 2015-08-11 12:12
thanks

**Closed by vmora** 2015-08-11 12:12 UTC
